import { Property } from "./types";

const properties: Property[] = [
  {
    id: "1",
    title: "Modern Downtown Apartment",
    slug: "modern-downtown-apartment",
    description:
      "Stunning modern apartment in the heart of the city. Floor-to-ceiling windows offer panoramic skyline views. Features an open-concept living area with Italian marble flooring, a chef's kitchen with Miele appliances, and a spacious master suite with a walk-in closet. Building amenities include a 24-hour concierge, rooftop pool, fitness center, and private parking.",
    price: 450000,
    location: "123 Main Street, Downtown, NY 10001",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    image: "https://picsum.photos/seed/prop1/800/600",
    images: [
      "https://picsum.photos/seed/prop1a/800/600",
      "https://picsum.photos/seed/prop1b/800/600",
      "https://picsum.photos/seed/prop1c/800/600",
    ],
    type: "apartment",
    yearBuilt: 2020,
    amenities: ["Parking", "Gym", "Pool", "Concierge", "Rooftop Terrace"],
    agentName: "Sarah Johnson",
    agentPhone: "(212) 555-0101",
    agentEmail: "sarah.johnson@realty.com",
    latitude: 40.7128,
    longitude: -74.006,
  },
  {
    id: "2",
    title: "Suburban Family Home",
    slug: "suburban-family-home",
    description:
      "Beautiful 4-bedroom family home nestled in a quiet, tree-lined neighborhood. The gourmet kitchen features quartz countertops and stainless steel appliances. A spacious backyard with a deck is perfect for entertaining. Top-rated school district, close to parks, shopping, and major highways. Move-in ready with fresh paint and new flooring throughout.",
    price: 625000,
    location: "456 Oak Avenue, Suburbia, NY 10002",
    bedrooms: 4,
    bathrooms: 3,
    area: 2400,
    image: "https://picsum.photos/seed/prop2/800/600",
    images: [
      "https://picsum.photos/seed/prop2a/800/600",
      "https://picsum.photos/seed/prop2b/800/600",
    ],
    type: "house",
    yearBuilt: 2015,
    amenities: ["Garage", "Backyard", "Deck", "Central AC", "Smart Home"],
    agentName: "Michael Chen",
    agentPhone: "(516) 555-0202",
    agentEmail: "michael.chen@realty.com",
    latitude: 40.758,
    longitude: -73.9855,
  },
  {
    id: "3",
    title: "Luxury Beachfront Villa",
    slug: "luxury-beachfront-villa",
    description:
      "Exquisite beachfront villa offering unparalleled ocean views and direct beach access. This architecturally designed home features soaring ceilings, floor-to-ceiling windows, and premium finishes throughout. The outdoor living space includes an infinity pool, outdoor kitchen, and lush tropical landscaping. A private dock provides direct water access.",
    price: 1895000,
    location: "789 Ocean Drive, Malibu, CA 90265",
    bedrooms: 5,
    bathrooms: 4,
    area: 4500,
    image: "https://picsum.photos/seed/prop3/800/600",
    images: [
      "https://picsum.photos/seed/prop3a/800/600",
      "https://picsum.photos/seed/prop3b/800/600",
      "https://picsum.photos/seed/prop3c/800/600",
    ],
    type: "villa",
    yearBuilt: 2018,
    amenities: [
      "Infinity Pool",
      "Private Beach Access",
      "Outdoor Kitchen",
      "Home Theater",
      "Wine Cellar",
    ],
    agentName: "Jessica Williams",
    agentPhone: "(310) 555-0303",
    agentEmail: "jessica.williams@realty.com",
    latitude: 34.0259,
    longitude: -118.7798,
  },
  {
    id: "4",
    title: "Cozy Studio Loft",
    slug: "cozy-studio-loft",
    description:
      "Charming industrial-style studio loft in a converted warehouse. Exposed brick walls, polished concrete floors, and 14-foot ceilings create a spacious living environment. The kitchen features custom cabinetry and butcher block countertops. Located in a vibrant arts district with galleries, cafes, and boutiques steps from your door.",
    price: 275000,
    location: "321 Arts District Lane, Portland, OR 97201",
    bedrooms: 1,
    bathrooms: 1,
    area: 650,
    image: "https://picsum.photos/seed/prop4/800/600",
    images: [
      "https://picsum.photos/seed/prop4a/800/600",
      "https://picsum.photos/seed/prop4b/800/600",
    ],
    type: "apartment",
    yearBuilt: 1920,
    amenities: ["Bike Storage", "Laundry", "Pet Friendly"],
    agentName: "Alex Rivera",
    agentPhone: "(503) 555-0404",
    agentEmail: "alex.rivera@realty.com",
    latitude: 45.5152,
    longitude: -122.6784,
  },
  {
    id: "5",
    title: "Mountain Retreat Cabin",
    slug: "mountain-retreat-cabin",
    description:
      "Secluded log cabin nestled in the mountains with breathtaking views. This handcrafted timber home features a stone fireplace, gourmet kitchen, and a wraparound porch. The property includes 10 acres of pristine forest with a private hiking trail. Perfect as a vacation home or full-time residence for nature lovers.",
    price: 520000,
    location: "555 Pine Trail, Aspen, CO 81611",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    image: "https://picsum.photos/seed/prop5/800/600",
    images: [
      "https://picsum.photos/seed/prop5a/800/600",
      "https://picsum.photos/seed/prop5b/800/600",
      "https://picsum.photos/seed/prop5c/800/600",
    ],
    type: "house",
    yearBuilt: 2005,
    amenities: ["Fireplace", "Hot Tub", "Deck", "Hiking Trails", "Generator"],
    agentName: "David Thompson",
    agentPhone: "(970) 555-0505",
    agentEmail: "david.thompson@realty.com",
    latitude: 39.1911,
    longitude: -106.8175,
  },
  {
    id: "6",
    title: "Penthouse with Panoramic Views",
    slug: "penthouse-panoramic-views",
    description:
      "Breathtaking penthouse suite occupying the entire 50th floor. Floor-to-ceiling windows provide 360-degree views of the city skyline. The interior boasts custom millwork, a private elevator foyer, and a grand salon with a gas fireplace. The primary suite includes a spa-like bathroom with a soaking tub and steam shower.",
    price: 3200000,
    location: "100 Skyline Boulevard, Chicago, IL 60601",
    bedrooms: 3,
    bathrooms: 3,
    area: 3200,
    image: "https://picsum.photos/seed/prop6/800/600",
    images: [
      "https://picsum.photos/seed/prop6a/800/600",
      "https://picsum.photos/seed/prop6b/800/600",
    ],
    type: "condo",
    yearBuilt: 2022,
    amenities: ["Private Elevator", "Wine Cellar", "Home Office", "Terrace"],
    agentName: "Rachel Kim",
    agentPhone: "(312) 555-0606",
    agentEmail: "rachel.kim@realty.com",
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    id: "7",
    title: "Charming Victorian Townhouse",
    slug: "charming-victorian-townhouse",
    description:
      "Beautifully restored Victorian townhouse blending historic charm with modern amenities. Original hardwood floors, crown moldings, and a grand staircase have been meticulously preserved. The updated kitchen features marble countertops and professional-grade appliances. A private garden and rooftop terrace provide outdoor living spaces.",
    price: 875000,
    location: "77 Heritage Way, Boston, MA 02108",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    image: "https://picsum.photos/seed/prop7/800/600",
    images: [
      "https://picsum.photos/seed/prop7a/800/600",
      "https://picsum.photos/seed/prop7b/800/600",
    ],
    type: "house",
    yearBuilt: 1890,
    amenities: ["Garden", "Fireplace", "Rooftop Terrace", "Wine Cellar"],
    agentName: "Emily Foster",
    agentPhone: "(617) 555-0707",
    agentEmail: "emily.foster@realty.com",
    latitude: 42.3601,
    longitude: -71.0589,
  },
  {
    id: "8",
    title: "Modern Waterfront Condo",
    slug: "modern-waterfront-condo",
    description:
      "Sleek waterfront condo with stunning marina views. Open-concept design with floor-to-ceiling windows, European cabinetry, and smart home technology. The building offers resort-style amenities including a swimming pool, tennis courts, and a private marina with boat slips available.",
    price: 580000,
    location: "200 Harbor Drive, Miami, FL 33139",
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    image: "https://picsum.photos/seed/prop8/800/600",
    images: [
      "https://picsum.photos/seed/prop8a/800/600",
      "https://picsum.photos/seed/prop8b/800/600",
    ],
    type: "condo",
    yearBuilt: 2019,
    amenities: [
      "Pool",
      "Tennis Court",
      "Marina Access",
      "Gym",
      "Concierge",
    ],
    agentName: "Carlos Mendez",
    agentPhone: "(305) 555-0808",
    agentEmail: "carlos.mendez@realty.com",
    latitude: 25.7617,
    longitude: -80.1918,
  },
  {
    id: "9",
    title: "Historic Farmhouse Estate",
    slug: "historic-farmhouse-estate",
    description:
      "Magnificent farmhouse estate on 20 acres of rolling countryside. The main residence features 6 bedrooms, a country kitchen with a wood-burning fireplace, and a screened porch. Property includes a barn, guest house, and organic garden. Ideal for those seeking a peaceful rural lifestyle with modern comforts.",
    price: 1250000,
    location: "1000 Country Road, Hudson Valley, NY 12534",
    bedrooms: 6,
    bathrooms: 4,
    area: 5000,
    image: "https://picsum.photos/seed/prop9/800/600",
    images: [
      "https://picsum.photos/seed/prop9a/800/600",
      "https://picsum.photos/seed/prop9b/800/600",
      "https://picsum.photos/seed/prop9c/800/600",
    ],
    type: "house",
    yearBuilt: 1850,
    amenities: [
      "Barn",
      "Guest House",
      "Organic Garden",
      "Pond",
      "Fireplace",
    ],
    agentName: "Patricia O'Brien",
    agentPhone: "(518) 555-0909",
    agentEmail: "patricia.obrien@realty.com",
    latitude: 42.0528,
    longitude: -73.9067,
  },
  {
    id: "10",
    title: "Urban Loft with Rooftop",
    slug: "urban-loft-rooftop",
    description:
      "Stylish urban loft in a converted factory building. The expansive open floor plan features 20-foot ceilings, massive windows, and original steel beams. The modern kitchen is equipped with top-of-the-line appliances. A private rooftop terrace offers stunning city views and is perfect for entertaining.",
    price: 395000,
    location: "88 Industrial Street, Brooklyn, NY 11201",
    bedrooms: 1,
    bathrooms: 1,
    area: 900,
    image: "https://picsum.photos/seed/prop10/800/600",
    images: [
      "https://picsum.photos/seed/prop10a/800/600",
      "https://picsum.photos/seed/prop10b/800/600",
    ],
    type: "apartment",
    yearBuilt: 1925,
    amenities: ["Rooftop", "Laundry", "Bike Storage", "Pet Friendly"],
    agentName: "Jordan Lee",
    agentPhone: "(718) 555-1010",
    agentEmail: "jordan.lee@realty.com",
    latitude: 40.6782,
    longitude: -73.9442,
  },
  {
    id: "11",
    title: "Eco-Friendly Smart Home",
    slug: "eco-friendly-smart-home",
    description:
      "Net-zero energy smart home with solar panels, geothermal heating, and a green roof. This sustainably designed residence features a rainwater collection system, energy-efficient appliances, and smart home automation. The open-concept interior is filled with natural light and features sustainable materials throughout.",
    price: 720000,
    location: "42 Green Way, Austin, TX 78701",
    bedrooms: 3,
    bathrooms: 2,
    area: 2100,
    image: "https://picsum.photos/seed/prop11/800/600",
    images: [
      "https://picsum.photos/seed/prop11a/800/600",
      "https://picsum.photos/seed/prop11b/800/600",
    ],
    type: "house",
    yearBuilt: 2023,
    amenities: [
      "Solar Panels",
      "Smart Home",
      "EV Charger",
      "Green Roof",
      "Rainwater System",
    ],
    agentName: "Nate Thompson",
    agentPhone: "(512) 555-1111",
    agentEmail: "nate.thompson@realty.com",
    latitude: 30.2672,
    longitude: -97.7431,
  },
  {
    id: "12",
    title: "Mediterranean Hilltop Villa",
    slug: "mediterranean-hilltop-villa",
    description:
      "Stunning Mediterranean-style villa perched on a hilltop with sweeping views of the coastline. The home features terracotta tile roofing, arched doorways, and a courtyard with a fountain. Outdoor living spaces include a loggia, infinity pool, and landscaped gardens with olive trees.",
    price: 2450000,
    location: "1 Vista Drive, Santa Barbara, CA 93101",
    bedrooms: 4,
    bathrooms: 5,
    area: 3800,
    image: "https://picsum.photos/seed/prop12/800/600",
    images: [
      "https://picsum.photos/seed/prop12a/800/600",
      "https://picsum.photos/seed/prop12b/800/600",
      "https://picsum.photos/seed/prop12c/800/600",
    ],
    type: "villa",
    yearBuilt: 2008,
    amenities: [
      "Infinity Pool",
      "Courtyard",
      "Outdoor Kitchen",
      "Wine Cellar",
    ],
    agentName: "Sofia Garcia",
    agentPhone: "(805) 555-1212",
    agentEmail: "sofia.garcia@realty.com",
    latitude: 34.4208,
    longitude: -119.6982,
  },
  {
    id: "13",
    title: "Starter Home in Growing Suburb",
    slug: "starter-home-growing-suburb",
    description:
      "Perfect starter home in a rapidly growing suburban community. Open floor plan with 3 bedrooms and a modern kitchen with granite countertops. The fenced backyard is ideal for children and pets. Close to new schools, shopping centers, and the commuter rail station.",
    price: 335000,
    location: "789 Maple Drive, Cary, NC 27513",
    bedrooms: 3,
    bathrooms: 2,
    area: 1400,
    image: "https://picsum.photos/seed/prop13/800/600",
    images: [
      "https://picsum.photos/seed/prop13a/800/600",
      "https://picsum.photos/seed/prop13b/800/600",
    ],
    type: "house",
    yearBuilt: 2018,
    amenities: ["Fenced Yard", "Garage", "Central AC"],
    agentName: "Megan Patel",
    agentPhone: "(919) 555-1313",
    agentEmail: "megan.patel@realty.com",
    latitude: 35.784,
    longitude: -78.7775,
  },
  {
    id: "14",
    title: "Ski-In Ski-Out Chalet",
    slug: "ski-in-ski-out-chalet",
    description:
      "Luxurious ski chalet with direct slope access. After a day on the mountain, relax in the hot tub or by the massive stone fireplace. The gourmet kitchen and open living area are perfect for entertaining. Features a ski room with heated boot warmers and a private sauna.",
    price: 1650000,
    location: "200 Snowy Peak Road, Park City, UT 84060",
    bedrooms: 5,
    bathrooms: 4,
    area: 3500,
    image: "https://picsum.photos/seed/prop14/800/600",
    images: [
      "https://picsum.photos/seed/prop14a/800/600",
      "https://picsum.photos/seed/prop14b/800/600",
    ],
    type: "villa",
    yearBuilt: 2012,
    amenities: [
      "Ski Access",
      "Hot Tub",
      "Sauna",
      "Fireplace",
      "Ski Room",
    ],
    agentName: "Erik Bergstrom",
    agentPhone: "(435) 555-1414",
    agentEmail: "erik.bergstrom@realty.com",
    latitude: 40.6461,
    longitude: -111.498,
  },
  {
    id: "15",
    title: "Mid-Century Modern Gem",
    slug: "mid-century-modern-gem",
    description:
      "Impeccably preserved mid-century modern home designed by a notable architect. The home features clean lines, floor-to-ceiling windows, and an open layout that seamlessly connects indoor and outdoor living spaces. Original details include terrazzo flooring, a butterfly roof, and a dramatic stone fireplace.",
    price: 890000,
    location: "555 Architecture Circle, Palm Springs, CA 92262",
    bedrooms: 3,
    bathrooms: 2,
    area: 1900,
    image: "https://picsum.photos/seed/prop15/800/600",
    images: [
      "https://picsum.photos/seed/prop15a/800/600",
      "https://picsum.photos/seed/prop15b/800/600",
    ],
    type: "house",
    yearBuilt: 1962,
    amenities: ["Pool", "Fireplace", "Patio", "Mountain Views"],
    agentName: "Diana Rossi",
    agentPhone: "(760) 555-1515",
    agentEmail: "diana.rossi@realty.com",
    latitude: 33.8303,
    longitude: -116.5453,
  },
  {
    id: "16",
    title: "Tech Hub Micro Apartment",
    slug: "tech-hub-micro-apartment",
    description:
      "Efficiently designed micro-apartment in the heart of the tech hub. Smart space-saving solutions include a murphy bed, fold-down desk, and modular storage. The building features co-working spaces, a gym, and regular community events. Ideal for young professionals working in the tech industry.",
    price: 185000,
    location: "100 Innovation Drive, San Francisco, CA 94107",
    bedrooms: 1,
    bathrooms: 1,
    area: 400,
    image: "https://picsum.photos/seed/prop16/800/600",
    images: [
      "https://picsum.photos/seed/prop16a/800/600",
      "https://picsum.photos/seed/prop16b/800/600",
    ],
    type: "apartment",
    yearBuilt: 2021,
    amenities: [
      "Co-working Space",
      "Gym",
      "Rooftop",
      "Package Room",
      "Bike Storage",
    ],
    agentName: "Kevin Wu",
    agentPhone: "(415) 555-1616",
    agentEmail: "kevin.wu@realty.com",
    latitude: 37.7749,
    longitude: -122.4194,
  },
  {
    id: "17",
    title: "Lakefront Cottage Retreat",
    slug: "lakefront-cottage-retreat",
    description:
      "Charming lakefront cottage with stunning sunset views over the water. This cozy home features a screened porch, private dock, and a stone fireplace. The property includes 100 feet of waterfront with a sandy beach area. Perfect for year-round living or as a weekend getaway.",
    price: 475000,
    location: "50 Lakeshore Drive, Lake George, NY 12845",
    bedrooms: 2,
    bathrooms: 1,
    area: 1100,
    image: "https://picsum.photos/seed/prop17/800/600",
    images: [
      "https://picsum.photos/seed/prop17a/800/600",
      "https://picsum.photos/seed/prop17b/800/600",
    ],
    type: "house",
    yearBuilt: 1985,
    amenities: ["Private Dock", "Fireplace", "Screened Porch", "Beach"],
    agentName: "Linda Adams",
    agentPhone: "(518) 555-1717",
    agentEmail: "linda.adams@realty.com",
    latitude: 43.425,
    longitude: -73.712,
  },
  {
    id: "18",
    title: "Artist's Warehouse Studio",
    slug: "artists-warehouse-studio",
    description:
      "Expansive warehouse studio perfect for artists and creatives. The main living space features 22-foot ceilings with north-facing skylights providing perfect natural light. A dedicated gallery space, storage room, and a separate living area. Located in a thriving arts community with monthly gallery walks.",
    price: 310000,
    location: "777 Creative Alley, Philadelphia, PA 19106",
    bedrooms: 1,
    bathrooms: 1,
    area: 1500,
    image: "https://picsum.photos/seed/prop18/800/600",
    images: [
      "https://picsum.photos/seed/prop18a/800/600",
      "https://picsum.photos/seed/prop18b/800/600",
    ],
    type: "apartment",
    yearBuilt: 1920,
    amenities: ["Skylight", "Gallery Space", "Storage", "Loading Dock"],
    agentName: "Marcus Webb",
    agentPhone: "(215) 555-1818",
    agentEmail: "marcus.webb@realty.com",
    latitude: 39.9526,
    longitude: -75.1652,
  },
  {
    id: "19",
    title: "Golf Course Estate",
    slug: "golf-course-estate",
    description:
      "Magnificent estate overlooking the 12th fairway of a championship golf course. The home features a grand foyer, formal living and dining rooms, and a gourmet kitchen. The master suite includes a sitting area, dual walk-in closets, and a spa bath. Community amenities include a clubhouse, tennis courts, and a pool.",
    price: 1450000,
    location: "100 Fairway Lane, Scottsdale, AZ 85254",
    bedrooms: 5,
    bathrooms: 4,
    area: 4200,
    image: "https://picsum.photos/seed/prop19/800/600",
    images: [
      "https://picsum.photos/seed/prop19a/800/600",
      "https://picsum.photos/seed/prop19b/800/600",
    ],
    type: "house",
    yearBuilt: 2016,
    amenities: [
      "Golf View",
      "Pool",
      "Clubhouse Access",
      "Tennis Court",
    ],
    agentName: "Robert Chen",
    agentPhone: "(480) 555-1919",
    agentEmail: "robert.chen@realty.com",
    latitude: 33.587,
    longitude: -111.935,
  },
  {
    id: "20",
    title: "Tiny House with Big Style",
    slug: "tiny-house-big-style",
    description:
      "Thoughtfully designed tiny house maximizing every square inch. This custom-built home features a loft bedroom, full kitchen, bathroom with a rain shower, and a living area with a fold-out sofa. Built on a trailer for mobility, includes solar power and a composting toilet system.",
    price: 85000,
    location: "15 Minimalist Way, Portland, OR 97202",
    bedrooms: 1,
    bathrooms: 1,
    area: 280,
    image: "https://picsum.photos/seed/prop20/800/600",
    images: [
      "https://picsum.photos/seed/prop20a/800/600",
      "https://picsum.photos/seed/prop20b/800/600",
    ],
    type: "house",
    yearBuilt: 2023,
    amenities: [
      "Solar Power",
      "Mobile",
      "Composting Toilet",
      "Loft",
    ],
    agentName: "Zoe Green",
    agentPhone: "(503) 555-2020",
    agentEmail: "zoe.green@realty.com",
    latitude: 45.5152,
    longitude: -122.6584,
  },
  {
    id: "21",
    title: "Colonial Brick Mansion",
    slug: "colonial-brick-mansion",
    description:
      "Grand colonial brick mansion on a prestigious tree-lined street. This 8-bedroom estate features a grand entrance hall with a marble staircase, a ballroom, library, and a conservatory. The meticulously manicured gardens include a rose garden, fountain, and a carriage house. A true piece of architectural history.",
    price: 4200000,
    location: "1 Heritage Square, Washington, DC 20001",
    bedrooms: 8,
    bathrooms: 6,
    area: 7500,
    image: "https://picsum.photos/seed/prop21/800/600",
    images: [
      "https://picsum.photos/seed/prop21a/800/600",
      "https://picsum.photos/seed/prop21b/800/600",
    ],
    type: "house",
    yearBuilt: 1925,
    amenities: [
      "Ballroom",
      "Library",
      "Conservatory",
      "Carriage House",
      "Garden",
    ],
    agentName: "William Hart",
    agentPhone: "(202) 555-2121",
    agentEmail: "william.hart@realty.com",
    latitude: 38.9072,
    longitude: -77.0369,
  },
  {
    id: "22",
    title: "Desert Modern Oasis",
    slug: "desert-modern-oasis",
    description:
      "Architectural desert modern home with breathtaking mountain views. Walls of glass blur the line between indoor and outdoor living. The home features a central courtyard with a reflecting pool, an outdoor shower, and a saltwater pool. Sustainable design includes passive cooling and solar energy systems.",
    price: 975000,
    location: "55 Desert Moon Road, Sedona, AZ 86336",
    bedrooms: 3,
    bathrooms: 3,
    area: 2600,
    image: "https://picsum.photos/seed/prop22/800/600",
    images: [
      "https://picsum.photos/seed/prop22a/800/600",
      "https://picsum.photos/seed/prop22b/800/600",
    ],
    type: "villa",
    yearBuilt: 2020,
    amenities: [
      "Saltwater Pool",
      "Courtyard",
      "Outdoor Shower",
      "Solar",
    ],
    agentName: "Amanda Stone",
    agentPhone: "(928) 555-2222",
    agentEmail: "amanda.stone@realty.com",
    latitude: 34.8697,
    longitude: -111.761,
  },
  {
    id: "23",
    title: "Condo with City Park Views",
    slug: "condo-city-park-views",
    description:
      "Elegant condo overlooking a beautiful city park. This well-appointed home features hardwood floors, a renovated kitchen with marble countertops, and a spacious balcony perfect for morning coffee. Building amenities include a doorman, gym, and rooftop garden. Steps from public transit and the best restaurants.",
    price: 495000,
    location: "30 Park Avenue, New York, NY 10016",
    bedrooms: 2,
    bathrooms: 1,
    area: 950,
    image: "https://picsum.photos/seed/prop23/800/600",
    images: [
      "https://picsum.photos/seed/prop23a/800/600",
      "https://picsum.photos/seed/prop23b/800/600",
    ],
    type: "condo",
    yearBuilt: 1995,
    amenities: ["Doorman", "Gym", "Rooftop Garden", "Laundry"],
    agentName: "Jennifer Park",
    agentPhone: "(212) 555-2323",
    agentEmail: "jennifer.park@realty.com",
    latitude: 40.7484,
    longitude: -73.9856,
  },
  {
    id: "24",
    title: "Wine Country Estate",
    slug: "wine-country-estate",
    description:
      "Spectacular wine country estate with a working vineyard producing award-winning wines. The main residence is a French country-style home with a gourmet kitchen, wine cellar, and terraces overlooking the vines. The property includes a guest cottage, tasting room, and a pool with panoramic valley views.",
    price: 3800000,
    location: "2000 Vineyard Road, Napa, CA 94558",
    bedrooms: 4,
    bathrooms: 4,
    area: 4800,
    image: "https://picsum.photos/seed/prop24/800/600",
    images: [
      "https://picsum.photos/seed/prop24a/800/600",
      "https://picsum.photos/seed/prop24b/800/600",
      "https://picsum.photos/seed/prop24c/800/600",
    ],
    type: "villa",
    yearBuilt: 2000,
    amenities: [
      "Vineyard",
      "Guest Cottage",
      "Tasting Room",
      "Pool",
      "Wine Cellar",
    ],
    agentName: "Isabella Rossi",
    agentPhone: "(707) 555-2424",
    agentEmail: "isabella.rossi@realty.com",
    latitude: 38.2975,
    longitude: -122.2869,
  },
];

export function getProperties(): Property[] {
  return properties;
}

export function getPropertyById(id: string): Property | undefined {
  return properties.find((p) => p.id === id);
}

export function getPropertyBySlug(slug: string): Property | undefined {
  return properties.find((p) => p.slug === slug);
}

export function searchProperties(query: string): Property[] {
  if (!query.trim()) return properties;
  const q = query.toLowerCase();
  return properties.filter(
    (p) =>
      p.title.toLowerCase().includes(q) ||
      p.location.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.type.toLowerCase().includes(q)
  );
}
